
services:
  db:
    image: postgres:14
    container_name: flashflicks_database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    container_name: flashflicks_django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      #DATABASE_URL: postgres://postgres:postgres@flashflicks_database:5432/postgres
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres



volumes:
  postgres_data:
